server:
  port: 8090
  compression:
    enabled: true
    min-response-size: 2048
    mime-types: text/html,text/xml,text/plain,text/css,application/json,application/xml,application/javascript
  servlet:
    contextPath: /
    session:
      timeout: 1h
    multipart:
      max-request-size: 30MB
      max-file-size: 10MB

---
spring:
  main:
    banner-mode: console
    allow-bean-definition-overriding: false
  output:
    ansi:
      enabled: ALWAYS
  flyway:
    enabled: false


  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
    jdbcUrl: jdbc:h2:mem:digitaldb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
  batch:
    jdbc:
      initialize-schema: always


---
logging:
  config: classpath:logback-console.xml

---
hibernate:
  hbm2ddl:
    auto: update
---
spring:
  main:
    allow-bean-definition-overriding: true
  devtools:
    active: dev
    restart:
      enabled: false
---
app:
  username: useradmin@digital.com
  bypassAuthentication: true
  errorLevel: 1
  jwtSecret: awlifhwaukfbwakfbwaukfwaghawvgcddthien@2021
  dummyDataEnabled: true
  jwtExpirationMs: 86400000
  password: useradmin@123