server:
  port: 7080
  compression:
    enabled: true
    min-response-size: 2048
    mime-types: text/html,text/xml,text/plain,text/css,application/json,application/xml,application/javascript
  servlet:
    contextPath: /
    session:
      timeout: 1h
    multipart:
      max-request-size: 30MB
      max-file-size: 10MB

---
spring:
  main:
    banner-mode: console
    allow-bean-definition-overriding: false
  output:
    ansi:
      enabled: ALWAYS


  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
    jdbcUrl: jdbc:h2:mem:digitaldb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
  batch:
    jdbc:
      initialize-schema: always
  h2:
    console:
      enabled: true
  hibernate:
    dialect: org.hibernate.dialect.H2Dialect
---
hibernate:
  dialect: org.hibernate.dialect.H2Dialect

---
logging:
  config: classpath:logback-console.xml

---
hibernate:
  hbm2ddl:
    auto: update
---
#openssl rand 256 | base64
jwt:
  auth:
    secret_key: qhb2u7t9LghE+TYarT2hVZZI4HqgF4ACrAji4TPWLzYnP7CzaIKFxjzJUoN1DiOwTfe7nvMjfEbz
  2+KuS8s64pn5dsxuOuExCga2fOLZoCU9ZKukx/fhVa06dt0MhpWPZfkiJ3eHmz1f3xO3gLEpUs90
  cXKfWsQk9Dq8VQ0K/pDk/rpVE0xRIkcdTvbklJAZwTi34IQHZTTyY5Qp3Zaayymrop2cWR8IZhSh
  pKrg8aHa2PTZdeWS+hdZ0ryC2LeLh0i0z68Exn0tI38dpBC3fPWs1F5wSO8jdfdtnzkFKVbf1FYs
  DbDZSZy87q/R58Z8nQB1B/n2CIBZha0kkozyCQ==
    expires_in: 3600
    app: DigitalVfx
